version: '3.2'
services:
  zoo1:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      vpcbr:
        ipv4_address: 172.16.0.56

  # kafka version: 1.1.0
  # scala version: 2.12
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
      - "9909:9909"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.16.0.57
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "test1:1:1"
      JMX_PORT: 9909
    depends_on:
      - zoo1
    networks:
      vpcbr:
        ipv4_address: 172.16.0.57 
        
  kafmanager:
    image: deric/kafka-manager:1.3.3.18
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zoo1:2181"
    depends_on:
      - zoo1
      - kafka
    networks:
      vpcbr:
        ipv4_address: 172.16.0.59

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 172.16.0.0/16
